on:
  # TODO: This should run for only pull requests for this repository's LTS branches
  pull_request:
name: LTS Library Test
jobs:
  lts-library-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - google-api-java-client
          - google-auth-library-java
          - google-http-java-client
          - google-maps-services-java
          - google-oauth-java-client
          - grpc-java
          - java-bigquery
          - java-bigtable-hbase
          - java-monitoring
          - java-pubsub
          - java-spanner
          - java-storage
          - java-trace
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: ./lts-test
        with:
          repository: ${{ matrix.repository }}